/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojacalcados.views;

import com.mycompany.lojacalcados.dao.ProdutoDAO;
import com.mycompany.lojacalcados.dao.ProdutoTamanhoDAO;
import com.mycompany.lojacalcados.models.Cliente;
import com.mycompany.lojacalcados.utils.Validador;
import com.mycompany.lojacalcados.models.Produto;
import com.mycompany.lojacalcados.models.ProdutoTamanho;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlConsulta = new javax.swing.JTabbedPane();
        pnlCadastroProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTituloProduto = new javax.swing.JTextField();
        txtPrecoProduto = new javax.swing.JTextField();
        btnCancelarProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        btnAdicionarProduto = new javax.swing.JButton();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxSexoProdutoCadastro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        pnlConsultaProduto = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtNomeProdutoPesquisar = new javax.swing.JTextField();
        btnProcurarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnAlterarProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTamanhos = new javax.swing.JTable();
        btnAlterarProdutoTamanho = new javax.swing.JButton();
        btnAdicionarProdutoTamanho = new javax.swing.JButton();
        btnExcluirTamanhoProduto = new javax.swing.JButton();
        btnProcurarProduto1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço:");

        jLabel6.setText("Marca:");

        txtTituloProduto.setName("Titulo"); // NOI18N
        txtTituloProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloProdutoActionPerformed(evt);
            }
        });

        txtPrecoProduto.setName("Preço"); // NOI18N
        txtPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdutoActionPerformed(evt);
            }
        });

        btnCancelarProduto.setText("Cancelar");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Id:");

        txtCodigoProduto.setEditable(false);
        txtCodigoProduto.setName("Código"); // NOI18N
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        btnAdicionarProduto.setText("Salvar");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        cbxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adidas", "Asics", "Converse", "Gucci", "Jordan", "New Balance", "Nike", "Prada", "Puma", "Rebook", "Outra" }));
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });

        cbxSexoProdutoCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Unissex" }));
        cbxSexoProdutoCadastro.setName("Sexo");
        cbxSexoProdutoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoProdutoCadastroActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo:");

        javax.swing.GroupLayout pnlCadastroProdutoLayout = new javax.swing.GroupLayout(pnlCadastroProduto);
        pnlCadastroProduto.setLayout(pnlCadastroProdutoLayout);
        pnlCadastroProdutoLayout.setHorizontalGroup(
            pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addComponent(btnCancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                        .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxSexoProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                                    .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTituloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCadastroProdutoLayout.setVerticalGroup(
            pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroProdutoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxSexoProdutoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarProduto)
                    .addComponent(btnAdicionarProduto))
                .addGap(70, 70, 70))
        );

        pnlConsulta.addTab("Cadastrar", pnlCadastroProduto);

        jLabel14.setText("Nome:");

        txtNomeProdutoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoPesquisarActionPerformed(evt);
            }
        });

        btnProcurarProduto.setText("Procurar");
        btnProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarProdutoActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Marca", "Sexo", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        btnAlterarProduto.setText("Alterar");
        btnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamanhos");

        tblTamanhos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Tamanho", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTamanhos);

        btnAlterarProdutoTamanho.setText("Alterar");
        btnAlterarProdutoTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProdutoTamanhoActionPerformed(evt);
            }
        });

        btnAdicionarProdutoTamanho.setText("Adicionar");
        btnAdicionarProdutoTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoTamanhoActionPerformed(evt);
            }
        });

        btnExcluirTamanhoProduto.setText("Excluir");
        btnExcluirTamanhoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTamanhoProdutoActionPerformed(evt);
            }
        });

        btnProcurarProduto1.setText("Det. Tamanhos");
        btnProcurarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarProduto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaProdutoLayout = new javax.swing.GroupLayout(pnlConsultaProduto);
        pnlConsultaProduto.setLayout(pnlConsultaProdutoLayout);
        pnlConsultaProdutoLayout.setHorizontalGroup(
            pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterarProdutoTamanho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionarProdutoTamanho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirTamanhoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNomeProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnProcurarProduto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAlterarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProcurarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        pnlConsultaProdutoLayout.setVerticalGroup(
            pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btnProcurarProduto))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(btnAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcurarProduto1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(btnAlterarProdutoTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarProdutoTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirTamanhoProduto))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlConsulta.addTab("Consultar", pnlConsultaProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeProdutoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoPesquisarActionPerformed

    private void btnProcurarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarProduto1ActionPerformed
        atualizarTabelaTamanhos(0);
    }//GEN-LAST:event_btnProcurarProduto1ActionPerformed

    private void btnProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarProdutoActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btnProcurarProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        int linhaSelecionada = tblProdutos.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            
            DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
            int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            
            boolean retorno = ProdutoDAO.excluir(idExcluir);
            
            if(retorno){
                JOptionPane.showMessageDialog(rootPane, "Produto excluido com sucesso");
                atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao excluir produto");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhum produto foi selecionado");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void cbxSexoProdutoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoProdutoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoProdutoCadastroActionPerformed

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed
        try {

            Validador.validarObrigatorio(txtTituloProduto);
            var retornoValidador = Validador.validarValor(txtPrecoProduto);
            
            if(!retornoValidador)
                return;
            
            String nome = txtTituloProduto.getText();
            String sexo = String.valueOf(cbxSexoProdutoCadastro.getSelectedItem());            
            String marca = String.valueOf(cbxMarca.getSelectedItem());
            Double preco = Double.parseDouble(txtPrecoProduto.getText());
            
            
            Produto produto = new Produto(nome, marca, preco, sexo );

            if(txtCodigoProduto.getText().isEmpty())
            {
                int idProdutoGerado = ProdutoDAO.adicionar(produto);
            
                if(idProdutoGerado > 0){
                    JOptionPane.showMessageDialog(rootPane, "O Produto foi cadastrado com sucesso");
                    TelaProdutoTamanho telaProdutoTamanho = new TelaProdutoTamanho();
                    telaProdutoTamanho.setVisible(true);
                    telaProdutoTamanho.setCodigoProdutoAdicionado(String.valueOf(idProdutoGerado));
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrar produto");
                }
                
            }else{
                produto.setId(Integer.parseInt(txtCodigoProduto.getText()));
                        
                boolean retorno = ProdutoDAO.alterar(produto);
                
                 if (retorno) 
                     JOptionPane.showMessageDialog(rootPane, "Produto atualizado com sucesso!");
                 else
                     JOptionPane.showMessageDialog(rootPane, "Falha ao atualizar!");
                 
            }
           
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    private void txtPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoProdutoActionPerformed

    private void txtTituloProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloProdutoActionPerformed

    private void btnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoActionPerformed
        DefaultTableModel modeloProduto = (DefaultTableModel) tblProdutos.getModel();
        int linhaSelecionada = tblProdutos.getSelectedRow();
        
        if(linhaSelecionada >= 0)
        {
            String id = String.valueOf(modeloProduto.getValueAt(linhaSelecionada, 0));
            String nome = String.valueOf(modeloProduto.getValueAt(linhaSelecionada, 1));
            String marca = String.valueOf(modeloProduto.getValueAt(linhaSelecionada, 2));
            String sexo = String.valueOf(modeloProduto.getValueAt(linhaSelecionada, 3));
            String preco = String.valueOf(modeloProduto.getValueAt(linhaSelecionada, 4));

            pnlConsulta.setSelectedIndex(0);
            txtCodigoProduto.setText(id);
            txtTituloProduto.setText(nome);
            cbxSexoProdutoCadastro.setSelectedItem(sexo);            
            cbxMarca.setSelectedItem(marca);
            txtPrecoProduto.setText(preco);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhum registro foi selecionado");
        }
    }//GEN-LAST:event_btnAlterarProdutoActionPerformed

    private void btnAlterarProdutoTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProdutoTamanhoActionPerformed
        
        int linhaSelecionada = tblTamanhos.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            
            DefaultTableModel modeloTabela = (DefaultTableModel) tblTamanhos.getModel();
            
            DefaultTableModel modeloTabelaProduto = (DefaultTableModel) tblProdutos.getModel();
            int idProduto = Integer.parseInt(modeloTabelaProduto.getValueAt(linhaSelecionada, 0).toString());
            
            int idTamanho = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            int tamanho = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 1).toString());
            int qtd = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 2).toString());
            
            ProdutoTamanho produtoTamanho = new ProdutoTamanho(idTamanho, idProduto, tamanho, qtd);
            TelaProdutoTamanho telaProdutoTamanho = new TelaProdutoTamanho();
            telaProdutoTamanho.setVisible(true);
            telaProdutoTamanho.setItensAlterar(produtoTamanho);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhum tamanho foi selecionado");
        }
    }//GEN-LAST:event_btnAlterarProdutoTamanhoActionPerformed

    private void btnExcluirTamanhoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTamanhoProdutoActionPerformed
        int linhaSelecionada = tblTamanhos.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            
            DefaultTableModel modeloTabela = (DefaultTableModel) tblTamanhos.getModel();
            int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            
            boolean retorno = ProdutoTamanhoDAO.excluir(idExcluir);
            
            if(retorno){
                JOptionPane.showMessageDialog(rootPane, "Tamanho excluido com sucesso");
                atualizarTabelaTamanhos(0);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao excluir tamanho");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhum tamanho foi selecionado");
        }
    }//GEN-LAST:event_btnExcluirTamanhoProdutoActionPerformed

    private void btnAdicionarProdutoTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoTamanhoActionPerformed
        int linhaSelecionada = tblProdutos.getSelectedRow();
        
        if(linhaSelecionada >= 0){          
            DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
            int idProduto = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            TelaProdutoTamanho telaProdutoTamanho = new TelaProdutoTamanho();
            telaProdutoTamanho.setVisible(true);
            telaProdutoTamanho.setCodigoProdutoAdicionado(String.valueOf(idProduto));
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nenhum produto foi selecionado");
        }
    }//GEN-LAST:event_btnAdicionarProdutoTamanhoActionPerformed
    
    public void atualizarTabela(){
         
        ArrayList<Produto> lista = ProdutoDAO.consultar(txtNomeProdutoPesquisar.getText()); 
        
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
        
        modeloTabela.setRowCount(0);
        
        for (Produto item : lista)
        {
            modeloTabela.addRow(new String[]{
                String.valueOf(item.getId()),
                item.getNome(),
                item.getMarca(),                
                item.getSexo(),
                String.valueOf(item.getPreco())
            });
        }
    } 
    
    public void atualizarTabelaTamanhos(int idProduto){
         
        if(idProduto <= 0){
            int linhaSelecionada = tblProdutos.getSelectedRow();
            if(linhaSelecionada >= 0){
                DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
                idProduto = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada, 0).toString());
            }else{
                JOptionPane.showMessageDialog(rootPane, "Selecione um produto primeiro");
            }
        }
        
        ArrayList<ProdutoTamanho> lista = ProdutoTamanhoDAO.consultarByProduto(idProduto);

        DefaultTableModel modeloTabelaTamanho = (DefaultTableModel) tblTamanhos.getModel();

        modeloTabelaTamanho.setRowCount(0);

        for (ProdutoTamanho item : lista)
        {
            modeloTabelaTamanho.addRow(new String[]{
                String.valueOf(item.getId()),
                String.valueOf(item.getTamanho()),
                String.valueOf(item.getQuantidade())
            });
        }

       
    } 
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnAdicionarProdutoTamanho;
    private javax.swing.JButton btnAlterarProduto;
    private javax.swing.JButton btnAlterarProdutoTamanho;
    private javax.swing.JButton btnCancelarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnExcluirTamanhoProduto;
    private javax.swing.JButton btnProcurarProduto;
    private javax.swing.JButton btnProcurarProduto1;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxSexoProdutoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlCadastroProduto;
    private javax.swing.JTabbedPane pnlConsulta;
    private javax.swing.JPanel pnlConsultaProduto;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblTamanhos;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtNomeProdutoPesquisar;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtTituloProduto;
    // End of variables declaration//GEN-END:variables
}
