/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lojacalcados.views;

import com.mycompany.lojacalcados.dao.ClienteDAO;
import com.mycompany.lojacalcados.models.Cliente;
import com.mycompany.lojacalcados.utils.Validador;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TelaClientes extends javax.swing.JFrame {
    
    Cliente objalterar=null;
    
    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGuiasCliente = new javax.swing.JTabbedPane();
        pnlCadastrarCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeClienteCadastro = new javax.swing.JTextField();
        txtCpfClienteCadastro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtEmailClienteCadastro = new javax.swing.JTextField();
        txtFoneClienteCadastro = new javax.swing.JFormattedTextField();
        btnCancelarCadastroCliente = new javax.swing.JButton();
        btnAdicionarCadastroCliente = new javax.swing.JButton();
        jdcNascimentoClienteCadastro = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEndereçoClienteCadastro = new javax.swing.JTextField();
        cbxSexoClienteCadastro = new javax.swing.JComboBox<>();
        cbxEstadoCivilClienteCadastro = new javax.swing.JComboBox<>();
        pnlConsultarCliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnProcurarCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtNomeClienteProcurar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Telefone:");
        jLabel5.setName("Telefone"); // NOI18N

        jLabel4.setText("E-mail:");
        jLabel4.setName("E-mail"); // NOI18N

        jLabel3.setText("Nasc.:");
        jLabel3.setName("Nascimento"); // NOI18N

        jLabel1.setText("CPF:");
        jLabel1.setName("CPF"); // NOI18N

        jLabel2.setText("Nome:");
        jLabel2.setName("Nome"); // NOI18N

        txtNomeClienteCadastro.setName("nome"); // NOI18N
        txtNomeClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteCadastroActionPerformed(evt);
            }
        });

        try {
            txtCpfClienteCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteCadastroActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        txtIdCliente.setEnabled(false);
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtEmailClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteCadastroActionPerformed(evt);
            }
        });

        try {
            txtFoneClienteCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCancelarCadastroCliente.setText("Cancelar");
        btnCancelarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroClienteActionPerformed(evt);
            }
        });

        btnAdicionarCadastroCliente.setText("Salvar");
        btnAdicionarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCadastroClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo:");

        jLabel9.setText("Estado Civil:");

        jLabel10.setText("Endereço");

        cbxSexoClienteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        cbxSexoClienteCadastro.setSelectedItem(null);
        cbxSexoClienteCadastro.setName("Sexo");
        cbxSexoClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexoClienteCadastroActionPerformed(evt);
            }
        });

        cbxEstadoCivilClienteCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "União Estável", "Separado(a)" }));
        cbxEstadoCivilClienteCadastro.setSelectedItem(null);
        cbxEstadoCivilClienteCadastro.setName("Estado Civil");
        cbxEstadoCivilClienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoCivilClienteCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastrarClienteLayout = new javax.swing.GroupLayout(pnlCadastrarCliente);
        pnlCadastrarCliente.setLayout(pnlCadastrarClienteLayout);
        pnlCadastrarClienteLayout.setHorizontalGroup(
            pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnCancelarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAdicionarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFoneClienteCadastro)
                                    .addComponent(txtEmailClienteCadastro)))
                            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEndereçoClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(68, 68, 68))
                                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                        .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(46, 46, 46)))
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeClienteCadastro)
                                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                        .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCpfClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jdcNascimentoClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCadastrarClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)))
                                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxSexoClienteCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxEstadoCivilClienteCadastro, 0, 579, Short.MAX_VALUE))))))
                .addGap(102, 102, 102))
        );
        pnlCadastrarClienteLayout.setVerticalGroup(
            pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastrarClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCpfClienteCadastro)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jdcNascimentoClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxSexoClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxEstadoCivilClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEndereçoClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoneClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(pnlCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCadastroCliente)
                    .addComponent(btnAdicionarCadastroCliente))
                .addGap(30, 30, 30))
        );

        pnlGuiasCliente.addTab("Cadastrar", pnlCadastrarCliente);

        jLabel7.setText("Nome:");

        btnProcurarCliente.setText("Procurar");
        btnProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Nasc.", "Sexo", "Est. Civ.", "End.", "E-mail", "Fone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblClientes.setMinimumSize(new java.awt.Dimension(167, 0));
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setMinWidth(10);
            tblClientes.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblClientes.getColumnModel().getColumn(5).setMinWidth(50);
            tblClientes.getColumnModel().getColumn(8).setPreferredWidth(66);
        }

        javax.swing.GroupLayout pnlConsultarClienteLayout = new javax.swing.GroupLayout(pnlConsultarCliente);
        pnlConsultarCliente.setLayout(pnlConsultarClienteLayout);
        pnlConsultarClienteLayout.setHorizontalGroup(
            pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarClienteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeClienteProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        pnlConsultarClienteLayout.setVerticalGroup(
            pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeClienteProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlConsultarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlConsultarClienteLayout.createSequentialGroup()
                        .addComponent(btnProcurarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirCliente)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlGuiasCliente.addTab("Consultar", pnlConsultarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuiasCliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailClienteCadastroActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        int linhaSelecionada = tblClientes.getSelectedRow();
        if (linhaSelecionada>=0) {
            DefaultTableModel modeloClientes =(DefaultTableModel)tblClientes.getModel();
            int idExcluir = Integer.parseInt(String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 0)));
            
            boolean retorno = ClienteDAO.excluir(idExcluir);
            if (retorno) {
                JOptionPane.showMessageDialog(rootPane, "Cliente excluído com sucesso!");
                atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Falha ao excluir cliente");
            }
            
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        DefaultTableModel modeloClientes = (DefaultTableModel) tblClientes.getModel();
        int linhaSelecionada = tblClientes.getSelectedRow();
        
        if(linhaSelecionada >= 0)
        {
        int id = Integer.parseInt(String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 0)));
        String nome = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 1));
        String cpf = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 2));
        
        String nasc = (String)modeloClientes.getValueAt(linhaSelecionada, 3);
        SimpleDateFormat formata = new SimpleDateFormat("dd-MM-yyyy");
        Date nascimento=null;
            try {
                nascimento = formata.parse(nasc);
            } catch (ParseException ex) {
                Logger.getLogger(TelaClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        String sexo = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 4));
        String estadoCivil = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 5));
        String endereco = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 6));
        String email = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 7));
        String fone = String.valueOf(modeloClientes.getValueAt(linhaSelecionada, 8));
        
        objalterar = new Cliente(nome, cpf, nascimento, endereco, sexo, estadoCivil, email, fone);
        objalterar.setId(id);
        pnlGuiasCliente.setSelectedIndex(0);
        txtIdCliente.setText(String.valueOf(id));
        txtNomeClienteCadastro.setText(String.valueOf(nome));
        txtCpfClienteCadastro.setText(cpf);
        jdcNascimentoClienteCadastro.setDate(nascimento);
        cbxSexoClienteCadastro.setSelectedItem(sexo);
        cbxEstadoCivilClienteCadastro.setSelectedItem(estadoCivil);
        txtEndereçoClienteCadastro.setText(endereco);
        txtEmailClienteCadastro.setText(email);
        txtFoneClienteCadastro.setText(fone);
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha da tabela");
        }
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnCancelarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroClienteActionPerformed
       dispose();
    }//GEN-LAST:event_btnCancelarCadastroClienteActionPerformed

    private void btnAdicionarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCadastroClienteActionPerformed
        
        
        
        try{
            Validador.validarObrigatorio(txtNomeClienteCadastro);
            Validador.validarObrigatorio(cbxSexoClienteCadastro);
            Validador.validarObrigatorio(cbxEstadoCivilClienteCadastro);
            Validador.validarCPF(txtCpfClienteCadastro);
            Validador.validarDataNascimento(jdcNascimentoClienteCadastro);
            Validador.validarEmail(txtEmailClienteCadastro);   
            Validador.validarNumeroCelular(txtFoneClienteCadastro);
            
            
            String nome = txtNomeClienteCadastro.getText();
            String CPF = txtCpfClienteCadastro.getText();
            String email = txtEmailClienteCadastro.getText();
            Date nasc = jdcNascimentoClienteCadastro.getDate();
            String sexo = String.valueOf(cbxSexoClienteCadastro.getSelectedItem());
            String estadoCivil = String.valueOf(cbxEstadoCivilClienteCadastro.getSelectedItem());
            String telefone = txtFoneClienteCadastro.getText();
            String endereco = txtEndereçoClienteCadastro.getText();
            
            Boolean retornoBanco=false;
            
            if (objalterar!=null) {
                int id = Integer.parseInt(txtIdCliente.getText());
                objalterar = new Cliente(nome, CPF, nasc,endereco,sexo, estadoCivil, email, telefone);
                objalterar.setId(id);
                retornoBanco=ClienteDAO.alterar(objalterar);
                if (retornoBanco) {
                     JOptionPane.showMessageDialog(rootPane, "Cliente atualizado com sucesso!");                     
                 }else{
                     JOptionPane.showMessageDialog(rootPane, "Falha ao atualizar!");
                 }
            }else{
                Cliente objCadastrar = new Cliente(nome, CPF, nasc, endereco, sexo, estadoCivil, email, telefone);
                retornoBanco = ClienteDAO.Salvar(objCadastrar);
                if (retornoBanco) {
                     JOptionPane.showMessageDialog(rootPane, "Cliente cadastrado com sucesso!");
                     txtIdCliente.setText("");
                     txtNomeClienteCadastro.setText("");
                     txtCpfClienteCadastro.setText("");
                     txtEmailClienteCadastro.setText("");
                     jdcNascimentoClienteCadastro.setDate(null);
                     cbxEstadoCivilClienteCadastro.setSelectedItem(null);
                     cbxSexoClienteCadastro.setSelectedItem(null);
                     txtFoneClienteCadastro.setText("");
                     txtEndereçoClienteCadastro.setText("");
                     
                 }else{
                     JOptionPane.showMessageDialog(rootPane, "Falha ao cadastrar!");
                 }
            }
            
             
           
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            this.setBackground(Color.yellow);
        }
        
        
        
        
    }//GEN-LAST:event_btnAdicionarCadastroClienteActionPerformed

    private void txtCpfClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfClienteCadastroActionPerformed

    private void txtNomeClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteCadastroActionPerformed

    private void btnProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarClienteActionPerformed
        
        atualizarTabela();
        
    }//GEN-LAST:event_btnProcurarClienteActionPerformed

    public void atualizarTabela(){
    
         ArrayList<Cliente> lista = ClienteDAO.consultar();
        
        DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
        
        modeloTabela.setRowCount(0);
        
        for (Cliente item : lista) {
            SimpleDateFormat formata = new SimpleDateFormat("dd-MM-yyyy");
            if (txtNomeClienteProcurar.getText().isEmpty() || item.getNome().toLowerCase().contains(txtNomeClienteProcurar.getText().toLowerCase())) {
                 modeloTabela.addRow(new String[]{
                String.valueOf(item.getId()),
                item.getNome(),
                item.getCpf(),
               
                formata.format(item.getNascimento()),
                item.getSexo(),
                item.getEstadoCivil(),
                item.getEndereco(),
                item.getEmail(),
                item.getTelefone()
          
                });
            }
           
            
        }
    
    }
    
    private void cbxSexoClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexoClienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexoClienteCadastroActionPerformed

    private void cbxEstadoCivilClienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoCivilClienteCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoCivilClienteCadastroActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCadastroCliente;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnCancelarCadastroCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnProcurarCliente;
    private javax.swing.JComboBox<String> cbxEstadoCivilClienteCadastro;
    private javax.swing.JComboBox<String> cbxSexoClienteCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNascimentoClienteCadastro;
    private javax.swing.JPanel pnlCadastrarCliente;
    private javax.swing.JPanel pnlConsultarCliente;
    private javax.swing.JTabbedPane pnlGuiasCliente;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField txtCpfClienteCadastro;
    private javax.swing.JTextField txtEmailClienteCadastro;
    private javax.swing.JTextField txtEndereçoClienteCadastro;
    private javax.swing.JFormattedTextField txtFoneClienteCadastro;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomeClienteCadastro;
    private javax.swing.JTextField txtNomeClienteProcurar;
    // End of variables declaration//GEN-END:variables
}
